sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "xDq+KG8U3RgUpaDKZYjhSBiUJn9A4I2koIfcUP2CfgZSX6rjf9FrV7vvSByJxZuSG7v5mYu2FycnwAMjLmkcoSETh1hXpOZ2MNH1EDFltSlTLFN2DiM90DodM8qZhT2CosER/qm99iWWOyGhhHAKyqMmM1iQpgS1nLb3BVyaem3rpdxZdA79ozr6Y4TnOFUY9/mly1hc6N0k8YmIafQg8vcRQ1GU+0OYqR1xL5SLZmO65y+HhBZqLr4XbCZIKA5q+wmC3Qd3qLxMxtU9UUcTk7rMMsNh9O8ibyAzzlg8e9JPkOB/VBjMk8WaCFhka4PQmdXGe12y8UNAEgTLU1CP91eXvOUSI62pimH/7gt/VDF+mb3dW81ZUiyLmPbEVv1+68UjY3I79v+LjauCNJnwhJJIi5IFJHaes0MsyVD6sglI6w7P88FIGKWJUzHpYNAGZqItPO5TPHYMkZ4YrsO6EAWEAj95COesueiPdSbkGdiguvLUHTt8I8OfsUWtQpDLfsbe6/aXC+ndzUFblY1h7c85RoEPG9HYo/UQLgXZMw1wdPJ5vFnmfT+oHUCa0VCGpy0Y7LJD5dNkQsAYqXXTyxBX92rhdd0R2ZHeaiPRTU+G9CtPl/VhWtvFMbwvkllMC2j9YVqofuyt/VZfYMd32XfqURip7OWPp91zclsYSpY="
  - secure: "I90ab5DXX3gjFJ8+JRXxj5dNirAOLG/kjJ0Ce1kt1nIq+/LIKAoBW2OoYzPvbCTFJRw8IU11xlUJR8lqkSu0JaDb8NFqyGXi9rwPgQcmwTQJyhyfY4qX0q1bbbt6HIZ3JvDumCMGY1U6sr5KGqr4e1f0ZRJkpZxEHMiRYq4kJ1KyB2b9h61MSbPoQ6l/9zCVdzKqov2itZG7pUKlNY4P27N0hYadMPtx9cB0lJ2f81jMkp8oUhokw+Je2T9qLRqTYvglZTm0h7Taa7YaK4pZimU/ciz9Zq8w8hRlJd2m9num5K4Fs+paR+CJcTaIzfWUz7EPfnMILCkqWKkvUGQPP8conessn/Ps8HXDJUe1cqbtaANkTgpqhnpWqsYXo59sC9Syxsh66Bkb83kNsBfbR8MXvKl+rMzT0QICWfALiFt/V5CUE4dLFZ1Y8gdb/jzMWM4IRxG8Jwc0/A0REJ9qS7n1PyUENiY3zeCXJzesDNeQ15fpr+D3BUSWChjK7XI8k7FpnMQA7+riWIZn1bTDoQujkbVxnIVrKcS/ulKxTQ4eh2LemWJWjlgOMZcRE2cjyX5hSdFgNI0rmMLnrYWHpOwrTV0NTMuR1sjKSRbp4YSDcibbAjMfIyI2dZCQgW8jIQ9I4AF0vSe8psDvnim0yoVRkP0exJhEEDPFal+LIkA="
  - secure: "y9EHvfz4/sfNeT7pYRpnM/okMfSftSt9ztO8x3ef3IPLIpJc/fMFf0y4VEHlGMH+na2qHOe3edZwFbF9VhsEsFZa1NjKHd9MiMCUDt9sLnCZ40jhsfXwu0QPdvWTwwA30WlK/fsKfz6BPKApCBCoFzCs5plpXmbFEGoddOCXnKk6GDK3YdBRl3TaQQawdzQFMiXQdx7xvlQvIfhJJSMkrAl3G4XhpGTlHvoq7OGFuCiRu2tWFrlwNRvJdk0AkUaxivH8EUR07rkocAcRuY/4tbfstoB+eE2mbCk2jL7JPPaec9tmqL/VavgBa3IlYByEXCzvPlWv9nzO4CkRDyUpssXaJ2wzPXc5Lce5gSioNgeObmhVDG7oGmR7p+19upqPeVq6pOBYBtWF2uoYAEQ673VMSgnz4BNJal9rc+atxmQX7afVfNZRpXcnr0RfxEwF4R4R1DWf0KK7TqAGTJ5OKZKI9l4VQsZgMn1bAD1Cg5sOzQimbbqLjddlLKb6ljqWWRA/cXIRL8vn8cdqUa2IpJC8eJKCMzoGu/SeCWRdPiNNpKySuhkanU6nQ84E/8c0IXy0wrr/CnK7m3i6W89IWSREhnVpMtUSu3U+/UHNowZ73K4XELX2LvBHyDZIUxvhfYP9SSnJIqM9L3YHIeoAYDSh/1ibIBeiADz5AE5uxNg="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
