sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "t3M4OuaUM2nQmYQjY2rH+pzNW480Hxle6/saqKbgaxuqJXZe3B2oI4d/1GWZEtSZfrHiAcRbvcypem6/Vi/XDW0lR39J6eAU+yjS6KDWmGiBF11kZFDrIboQOJwNPyy51rbUCFkD0BIDkoY+RLP863xWipzS7r9se10wCr7fRwUlIFGarJLy+2m4tmhChHHeYjMPHtTd++CjS2HmVUE4tMhLPy6dRGYCCb1ugmcQzjuElCLjVb7HsBM5vPH/ffPfvuzm/A4ywgssrY8FCs2XVGeSW5rWgCOIx6/Nj3PYiF2ncaE18bSLVVoQXddAahbbi1OKsgn227925ZJ0oJ3nqfbj8IxZjacVx/Tty2JkVuetGlkHObLm3/Z9RJUuAgp2KadocDlxVNzmCl4d6lO4r+QMOXEAxfXzeEoZ2pFb7w1KBlrLR2Hpavup5uIEtFmykHk1E5YCncMrS/HoBzr0zR5xDjkb43DjP7SjxL4sISPb7y76RPqpm0XArq39UG2tvQiH+H4cE75KkWUHhdOmUGXR4WY9rJ83j5LGZ4/PoaLxbaPFj83ZPhQYIIsx3To6KDeA7H7W6tX4gD07Jzm+4tSylg+zE3Kl4SckDVeB+N45sLOw+oa7jR2xbm8zqtFSh1a35zGI0/RBWKDNBI6C7z1C4H2kBxQaBAh8X+pE7hM="
  - secure: "I90ab5DXX3gjFJ8+JRXxj5dNirAOLG/kjJ0Ce1kt1nIq+/LIKAoBW2OoYzPvbCTFJRw8IU11xlUJR8lqkSu0JaDb8NFqyGXi9rwPgQcmwTQJyhyfY4qX0q1bbbt6HIZ3JvDumCMGY1U6sr5KGqr4e1f0ZRJkpZxEHMiRYq4kJ1KyB2b9h61MSbPoQ6l/9zCVdzKqov2itZG7pUKlNY4P27N0hYadMPtx9cB0lJ2f81jMkp8oUhokw+Je2T9qLRqTYvglZTm0h7Taa7YaK4pZimU/ciz9Zq8w8hRlJd2m9num5K4Fs+paR+CJcTaIzfWUz7EPfnMILCkqWKkvUGQPP8conessn/Ps8HXDJUe1cqbtaANkTgpqhnpWqsYXo59sC9Syxsh66Bkb83kNsBfbR8MXvKl+rMzT0QICWfALiFt/V5CUE4dLFZ1Y8gdb/jzMWM4IRxG8Jwc0/A0REJ9qS7n1PyUENiY3zeCXJzesDNeQ15fpr+D3BUSWChjK7XI8k7FpnMQA7+riWIZn1bTDoQujkbVxnIVrKcS/ulKxTQ4eh2LemWJWjlgOMZcRE2cjyX5hSdFgNI0rmMLnrYWHpOwrTV0NTMuR1sjKSRbp4YSDcibbAjMfIyI2dZCQgW8jIQ9I4AF0vSe8psDvnim0yoVRkP0exJhEEDPFal+LIkA="
  - secure: "y9EHvfz4/sfNeT7pYRpnM/okMfSftSt9ztO8x3ef3IPLIpJc/fMFf0y4VEHlGMH+na2qHOe3edZwFbF9VhsEsFZa1NjKHd9MiMCUDt9sLnCZ40jhsfXwu0QPdvWTwwA30WlK/fsKfz6BPKApCBCoFzCs5plpXmbFEGoddOCXnKk6GDK3YdBRl3TaQQawdzQFMiXQdx7xvlQvIfhJJSMkrAl3G4XhpGTlHvoq7OGFuCiRu2tWFrlwNRvJdk0AkUaxivH8EUR07rkocAcRuY/4tbfstoB+eE2mbCk2jL7JPPaec9tmqL/VavgBa3IlYByEXCzvPlWv9nzO4CkRDyUpssXaJ2wzPXc5Lce5gSioNgeObmhVDG7oGmR7p+19upqPeVq6pOBYBtWF2uoYAEQ673VMSgnz4BNJal9rc+atxmQX7afVfNZRpXcnr0RfxEwF4R4R1DWf0KK7TqAGTJ5OKZKI9l4VQsZgMn1bAD1Cg5sOzQimbbqLjddlLKb6ljqWWRA/cXIRL8vn8cdqUa2IpJC8eJKCMzoGu/SeCWRdPiNNpKySuhkanU6nQ84E/8c0IXy0wrr/CnK7m3i6W89IWSREhnVpMtUSu3U+/UHNowZ73K4XELX2LvBHyDZIUxvhfYP9SSnJIqM9L3YHIeoAYDSh/1ibIBeiADz5AE5uxNg="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
